# -*- coding: utf-8 -*-
"""config1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZEZjXMBPhBs7GQAy7pY4upe2luTnWfc
"""

API_TOKEN = '5400431421:AAGR-1aN3bVQdwjNIdgfNv_J-YCRJZ0Hi58'